---
# tasks  for hadoop_master
- name: Download Java Packages
  get_url:
    url: https://mirrors.huaweicloud.com/java/jdk/8u171-b11/jdk-8u171-linux-x64.rpm
    dest: /root/java.rpm

- name: Download Hadoop Packages
  get_url:
    url: https://archive.apache.org/dist/hadoop/core/hadoop-1.2.1/hadoop-1.2.1-1.x86_64.rpm
    dest: /root/hadoop.rpm

- name: Install Both Packages
  command : "rpm -i /root/{{ item }} --force"
  loop: "{{ pkgs_name }}"

- name: Configure Hadoop core-site file 
  copy:
    src: "core-site.xml"
    dest: "/etc/hadoop/core-site.xml"

- name: Configure Hadoop hdfs-site file 
  template:
    src: "hdfs-site.xml.j2"
    dest: "/etc/hadoop/hdfs-site.xml"
        
- name: Create Directory for namenode
  file:
    path: "{{ hadoop_folder }}"
    state: directory
    
- name: Hadoop Namenode Format    
  shell: "echo Y | hadoop namenode -format"

- name: Start Namenode Service
  shell: "hadoop-daemon.sh start namenode"

- name: Make Hadoop Daemon Service Permanent
  lineinfile:
    path: /etc/rc.d/rc.local
    line: hadoop-daemon.sh start namenode
    mode: '0755'
