---
- hosts: localhost
  remote_user: ansible
  become: yes
  become_method: sudo
  gather_facts: no
  connection: ssh
  tasks:
   - name: Add group "siva" to remote server
     group:
       name: siva
       gid: 2010
       state: present

   - name: Add group "company" to remote server
     group:
       name: company
       gid: 2011
       state: present

   - name: Add group "team1" to remote server
     group:
       name: team1
       gid: 2012
       state: present 

   - name: Add user "sysadmin" to remote server
     user:
       name: sysadmin
       comment: "Privileged User"
       uid: 2001
       group: siva
       groups: company,team1
       append: yes
       shell: /bin/bash
       generate_ssh_key: yes
       ssh_key_bits: 2048
       ssh_key_file: .ssh/id_rsa

   - name: Add user "Bobin" to remote server
     user:
       name: bobin
       comment: "Accountant UnPrivileged User"
       uid: 2002
       group: company
       shell: /bin/bash
       generate_ssh_key: yes
       ssh_key_bits: 2048
       ssh_key_file: .ssh/id_rsa

   - name: Add user "Lonston" to remote server
     user:
       name: lonston
       comment: "Content creator UnPrivileged User"
       uid: 2003
       group: company
       shell: /bin/bash
       generate_ssh_key: yes
       ssh_key_bits: 2048
       ssh_key_file: .ssh/id_rsa

   - name: Add user "Rajesh" to remote server
     user:
       name: rajesh
       comment: "Unix Admin Privileged User"
       uid: 2004
       group: siva
       groups: company,team1
       append: yes
       shell: /bin/sh
       generate_ssh_key: yes
       ssh_key_bits: 2048
       ssh_key_file: .ssh/id_rsa

   - name: Add user "Guest001" to remote server
     user:
       name: guest001
       comment: "Temp account"
       uid: 2005
       group: team1
       shell: /bin/bash
       createhome: no
       password: ''
       expires: 1525198731

   - name: Force user "Guest001" to change the password
     command: 
         chage -d 0 guest001

   - name: Remove user "Games" from remote server
     user:
       name: games
       state: absent
       remove: yes
