- name: Delete instance(s)
  hosts: localhost 
  connection: local
  gather_facts: no

  vars:
    service_account_email: ansible@my-msc-2021.iam.gserviceaccount.com
    credentials_file: /var/lib/awx/projects/gcp_compute/my-msc-2021-15d636daf288.json
    project_id: my-msc-2021
    zone: us-central1-a
    instances: webserver 

  tasks:

    - name: Destroy instances

      gce:
        instance_names: "{{ instances }}"
        zone: "{{ zone }}"
        project_id: "{{ project_id }}"
        credentials_file: "{{ credentials_file }}"
        service_account_email: "{{ service_account_email }}"
        state: absent
